### ISSUE TITLE
create PNG's from a set of Mapbox layer id's

### ISSUE THREAD

**Issue by tomj** [greendrivendevs/map-gif-generator#1]
POST a set of layer id's (and creds?) somewhere (likely a Lambda API gateway endpoint) to have them grabbed from Mapbox and then put into an S3 bucket which will be watched by @ryanbateman

**Comment by tomj** [comment]
@ryanbateman so I just ran out the following 3 commands to prove this out:

1. `curl "https://api.mapbox.com/styles/v1/tomjtomj/cjyrmq6k600p61cmyw1cmk3fa?access_token=ACCESS_TOKEN" > style.json`
2. Edit `style.json` to remove unwanted layers and sources
3. `mbgl-render ./style.json out.png 2048 2048 -c -136.165420668035,58.9478304748497 -z 10 --token ACCESS_TOKEN` [This uses [mbgl-render](https://github.com/consbio/mbgl-renderer)]
4. repeat steps 2-4 for all layers in style.json

I'll stick it in a Docker container and plug it in to what you have already for GIF generation 🎉

**Comment by ryanbateman** [comment]
@tomj Nice! Would you like me to fire off a PR for my work back into the main repo?

**Comment by tomj** [comment]
@ryanbateman sounds good!  Will take a look at it later on 👌

**Comment by ryanbateman** [comment]
@tomj Just to clarify - "unwanted layers and sources" means any of the layers specified that I'm not directly rendering? i.e. if the layer IDs are '1', '2', and '3', remove 2&3 when rendering 1. Or are there additional layers/sources that you had in mind? Reason I ask is that there are a lot of dynamic/different layers here, so I'm wondering how exhaustive we need to be? (Also could you supply an example style file?")

**Comment by tomj** [comment]
@ryanbateman my wording could have been better :)

> i.e. if the layer IDs are '1', '2', and '3', remove 2&3 when rendering 1

is exactly correct.  I'll dig out a `style.json` for you also

**Comment by tomj** [comment]
Closing for now given a working concept of this can be found as of 9b1ba8d
